config/routes.rb
Aventurine::Application.routes.draw do
  devise_for :users

  root :to => 'home#index'
  
	resources :welcome
  resources :crystals

end

app/models/crystal.rb
class Crystal < ActiveRecord::Base
  attr_accessible :name
end

app/models/shard.rb
class Shard < ActiveRecord::Base
  belongs_to :user
  has_one :shard
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :displayName, :password, :password_confirmation, :remember_me
 
  has_many :shards, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/crystals_controller.rb
class CrystalsController < ApplicationController
  
  def index
    @crystals = Crystal.all
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	before_filter :check_user_logged_in

	def check_user_logged_in		
		redirect_to welcome_index_path unless user_signed_in?
	end
	
	def index
		
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  def index
    
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/crystals_helper.rb
module CrystalsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/crystals/index.html.erb
<%= render :partial => 'layouts/crystal_list', :locals => {:crystals => @crystals} %>

app/views/layouts/_crystal_list.html.erb
<div id="crystalList" class="resultsList">
  <% if crystals.empty? %>
    <div class="noResults">Your search did not return any results, please try altering your criteria.</div>
  <% else %>
    <% crystals.each do |crystal| %>
      <div class="display">
        <span id="name"><%= crystal.name %></span>
      </div>
    <% end %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Aventurine</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%- flash.each do |name, msg| -%>
  <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
<%- end -%>

<%= yield %>

</body>
</html>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/index.html.erb
<div id="container">
  <div id="logo"></div>
    <div id="login">
      <%= form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
        <div><%= f.email_field :email, :class => "textfield", :placeholder => "email" %></div>
        <div><%= f.password_field :password, :class => "textfield", :placeholder => "password" %></div>

        <div><%= f.submit "LOGIN", :class => "submitbutton" %></div>
      <% end %>
       <!-- end login-->
    </div>
        <div id="signup">
          <%= form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f| %>
            <%= devise_error_messages! %>
            <div><%= f.text_field :displayName, :class => "textfield", :placeholder => "display name" %></div>
            <div><%= f.email_field :email, :class => "textfield", :placeholder => "email" %></div>
            <div><%= f.password_field :password, :class => "textfield", :placeholder => "password" %></div>
            <div><%= f.password_field :password_confirmation, :class => "textfield", :placeholder => "confirm password" %></div>

            <div><%= f.submit "SIGN UP", :class => "submitbutton" %></div>
          <% end %>
        </div>
       <!--end signup-->

            <div id="blurb">
              <h1 class="title">What is Aventurine</h1>
              <p>    <a href="#" target="_self">I am a link!</a> <b>bold text</b> <s>strike through</s>
                <u>underlined</u>
                Rhoncus lorem nunc enim. Odio nunc dictumst amet et, facilisis? Lorem, aliquam, tortor urna tortor? Enim pulvinar lacus, diam mid nec nisi arcu egestas elementum sed, sed massa, cursus vel? Hac turpis vel cum tincidunt et porta aenean a placerat dis? Scelerisque, habitasse non! A? Sociis! Phasellus nunc? Velit velit arcu porttitor eu? Amet, porta nunc, sit integer a lorem! Porta ac amet diam enim. Pulvinar nisi pid placerat montes et mus? Tortor vel tincidunt risus natoque, scelerisque, ultrices scelerisque non integer sed mus massa dis in, ridiculus scelerisque eu sociis non et in, duis, arcu mid a duis velit? Proin dolor turpis! Sit phasellus nisi etiam nascetur, scelerisque duis auctor sit ridiculus ut enim a elementum ac nunc facilisis.
              </p>
              <!--end blurb-->
            </div>
  <!--<div id="clear"></div>
 <!--end container-->
</div>

<%= render "users/shared/links" %>